#! /bin/bash

bspc config wm_name                     bspwm

# Layout
bspc config top_padding                 18
bspc config border_width                3
bspc config window_gap                  3
bspc config split_ratio                 0.6

bspc config single_monocle              true
bspc config borderless_monocle          true
bspc config gapless_monocle             false
bspc config paddingless_monocle         false

# direction of second window
# first_child for the left (on landscape screen)
# second_child for the right (on landscape screen)
bspc config initial_polarity            first_child

bspc config history_aware_focus         true

bspc config click_to_focus              false
bspc config focus_follows_pointer       false

bspc config pointer_follows_monitor     true

# mod4 is windows key
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_corner

# cancel presel with another presel
bspc config auto_cancel                 true

# keep ratio when resizing certain windows
bspc config honor_size_hints            true

bspc config remove_unplugged_monitors   true
bspc config remove_disabled_monitors    true


# http://paletton.com/#uid=34r0u0kgJHN6oX3bWQhkPyZoTtA
bspc config focused_border_color        "#ECBC34"
bspc config active_border_color         "#000000"
bspc config normal_border_color         "#000000"
bspc config presel_feedback_color       "#A7BF81"
bspc config focused_locked_border_color "#C7B579"
bspc config active_locked_border_color  "#7E7F89"
bspc config normal_locked_border_color  "#3F3E3B"
bspc config urgent_border_color         "#EFA29A"


# Remove the bspwm logical monitor to remove its "Desktop"

#oldrose - VGA is clone of HDMI1
# bspc monitor VGA1 -r

#newrose - VGA is clone of LVDS1
bspc monitor LVDS1 -r
xrandr2-clone-vgaprime.sh
bspc monitor -r
# Fix background stretch after removing the internal monitor
feh --bg-fill --no-xinerama ~/.wallpapers/danielle_at_sea_flickr.jpg

# Rename initial desktop
bspc monitor -d A1 A2 A3 A4 A5 A6 A7 A8 A9 A0 A- A=



# if [[ `bspc query --monitors | wc -l` -gt 1 ]]; then
# 	# Switch to second monitor
# 	bspc monitor -f next
#
# 	# Rename and create desktops
# 	bspc monitor -d B1 B2 B3 B4 B5 B6 B7 B8 B9 B0 B- B=
#
# 	# Switch back to first monitor
# 	bspc monitor -f next
# fi

bspc config external_rules_command "$(which bspwm_external_rules)"


# Floating window rules
bspc rule -a Vlc         state = pseudo_tiled
bspc rule -a mpv         state = pseudo_tiled
bspc rule -a Pidgin      state = floating
bspc rule -a Pavucontrol state = floating
bspc rule -a Mixer       state = floating
bspc rule -a xfce4-panel state = floating
bspc rule -a qjackctl    state = floating
bspc rule -a Cadence     state = floating
bspc rule -a seq64       state = pseudo_tiled
bspc rule -a copyq       state = floating
bspc rule -a Arandr      state = floating
bspc rule -a "* Copying" state = floating
bspc rule -a QjackCtl    state = floating


# Default desktop rules
bspc rule -a "URxvt:ncmpcpp"       desktop=^1
bspc rule -a qBittorrent           desktop=^2
bspc rule -a soulseekqt.AppImage   desktop=^3
bspc rule -a SoulseekQt            desktop=^3
bspc rule -a Picard                desktop=^4
bspc rule -a Cadence               desktop=^5
bspc rule -a Carla                 desktop=^5
bspc rule -a qseq64                desktop=^6
bspc rule -a keepassxc             desktop=^8
bspc rule -a doublecmd             desktop=^9
bspc rule -a "Double Commander"    desktop=^9
bspc rule -a pcmanfm-qt            desktop=^9
bspc rule -a quassel               desktop=^11
bspc rule -a firefox               desktop=^12
bspc rule -a Chromium              desktop=^12


# Restore state (on reload)
# if [ -e "$BSPWM_STATE" ] ; then
# 	bspc wm -l "$BSPWM_STATE"
# 	rm "$BSPWM_STATE"
# fi

# Start the bar at the top
polybar sitting
# polybar standing

# Start a notifications daemon
# mako --default-timeout 8000 --width 600 --anchor top-center --background-color '#472877' --border-color '#ffffffaa'

bspwm_urgent_border
bspwm_enforce_loop
