# IgnorePath '/var/docker/*'
# IgnorePath '/var/log/*'
# IgnorePath '/var/tmp/*'
# IgnorePath '/var/backup/*'
# IgnorePath '/var/lib/docker/*'
# IgnorePath '/var/lib/pacman/*'
# IgnorePath '/var/lib/mysql/*'
# IgnorePath '/var/www/*'
# IgnorePath '/var/spool/*'
# IgnorePath '/var/aconfmgr/*'
IgnorePath '/var/*'
IgnorePath '/boot/*'
