#! /bin/sh

# Layout
bspc config top_padding         22
bspc config border_width        3
bspc config window_gap          3

# http://paletton.com/#uid=34r0u0kgJHN6oX3bWQhkPyZoTtA
bspc config focused_border_color "#ECBC34"
bspc config active_border_color "#000000"
bspc config normal_border_color "#000000"
bspc config presel_feedback_color "#A7BF81"
bspc config focused_locked_border_color "#C7B579"
bspc config active_locked_border_color "#7E7F89"
bspc config normal_locked_border_color "#3F3E3B"
bspc config urgent_border_color "#EFA29A"

bspc config focus_follows_pointer true
bspc config borderless_monocle  false
bspc config gapless_monocle     false
bspc config adaptative_raise    true
bspc config initial_polarity    second_child

# cancel presel with another presel
bspc config auto_cancel         true

bspc config wm_name bspwm
bspc config pointer_follows_monitor true
bspc config history_aware_focus true


# Rename and create desktops
bspc desktop -n A1
bspc monitor -d A1          # Reset for config changes as desktop is created on bspwm launch
bspc monitor -a A2 A3 A4

# Switch to second monitor
bspc monitor -f next

# Rename and create desktops
bspc desktop -n B1
bspc monitor -d B1          # Reset for config changes as desktop is created on bspwm launch
bspc monitor -a B2 B3 B4

# Switch back to first monitor
bspc monitor -f next


# Rules
bspc rule -a Vlc state=floating
bspc rule -a mpv state=floating
bspc rule -a cadence state=floating
bspc rule -a Chromium desktop=A1
# bspc rule -a Gimp desktop=A4
bspc rule -a Keepassx
bspc rule -a Pidgin state=floating
bspc rule -a Pavucontrol state=floating
bspc rule -a Mixer state=floating
bspc rule -a xfce4-panel state=floating
bspc rule -a qjackctl state=floating
bspc rule -a Cadence.py state=floating

# Reset monitor settings to use above (gh:143)
# bspc monitor -d B1 B2 B3 B4


export BSPWM_TREE=/tmp/bspwm-tree.json
export BSPWM_HISTORY=/tmp/bspwm-history.txt
export BSPWM_STACK=/tmp/bspwm-stack.txt

if [ -e "$BSPWM_TREE" ] ; then
	bspc restore -T "$BSPWM_TREE" -H "$BSPWM_HISTORY" -S "$BSPWM_STACK"
	rm "$BSPWM_TREE" "$BSPWM_HISTORY" "$BSPWM_STACK"
fi
